### ISSUE TITLE
Getting odd error on Windows

### ISSUE THREAD

**Issue by Callero** [tbielawa/bitmath#51]
'''Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from bitmath import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\bitmath\__init__.py", line 67, in <module>
ImportError: No module named fcntl'''

**Comment by Callero** [comment]
Solved!
Seems the module makes Unix style file locking calls using fcntl.

This thread was helpful:
http://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows

**Comment by tbielawa** [comment]
@Callero ACK. congrats, you're our first confirmed Win* user! 

Thanks for pointing this out to me. Though the problem in that SO thread was for file-locking, that's not exactly the case in this module. Specifically, in these highlighted lines here:

https://github.com/tbielawa/bitmath/blob/master/bitmath/__init__.py#L65-L68

The ``fcntl`` library is actually used much later in the module for calculating system disk capacities (reference: https://bitmath.readthedocs.org/en/latest/module.html#bitmath-query-device-capacity )

I think what I can do for you for now is add a conditional around those imports so they only evaluate on supported *NIX systems.

Following that quick-patch I'll open a new issue on the tracker to see if I can implement Win* support for device capacity reading. I think AWS has cheap enough Windows instances to test on.

**Comment by tbielawa** [comment]
Throwing a patch together right now that will fix your import error. Do note however that the ``query_device_capacity`` function will be unavailable until I can implement support for the proper system calls on windows.

**Comment by tbielawa** [comment]
@Callero if you would like to be notified of when windows support is available for the ``query_device_capacity`` function, please add yourself to the referenced issue: #52

**Comment by Callero** [comment]
Wow, lightning reactions there =)
Thanks!
