### ISSUE TITLE
best_prefix for negative values

### ISSUE THREAD

**Issue by mbdm** [tbielawa/bitmath#55]
The result of best_practive is always in Bits for negative values. It might be interesting to work on the absolute values, to get a more human readable result. Thanks for your work.

**Comment by tbielawa** [comment]
Can you give me an example so i can understand better and reproduce what
you're describing please?

Thanks!

**Comment by mbdm** [comment]
Ok, here is an example.

```
>>> bitmath.best_prefix(10**8)
MiB(95.367431640625)
>>> bitmath.best_prefix(-10**8)
Bit(-800000000.0)
```

The following result might be more readable.

```
>>> bitmath.best_prefix(10**8)
MiB(95.367431640625)
>>> bitmath.best_prefix(-10**8)
MiB(-95.367431640625)
```

**Comment by tbielawa** [comment]
Oh wow! Yeah. That's a bug actually, the way i see it. I'll prioritize this
and get working on a fix.

Thank you for contributing to open source! :-)

**Comment by mbdm** [comment]
Great. Thank you again. ;)

**Comment by tbielawa** [comment]
@mbdm I've got a fix prepared and I'm going to push it up in a minute. I'll update this ticket again once I push an updated release to PyPi

**Comment by mbdm** [comment]
Thanks. New release on PyPi works fine. ;)
