### ISSUE TITLE
Any way to control precision with best_prefix() methods????

### ISSUE THREAD

**Issue by tyan4g** [tbielawa/bitmath#61]
now I can convert the unit automaticly .

```
b_size = Byte(bucket.head_object(obj_name).content_length)
 return b_size.best_prefix().__str__()  //379.051757812 KiB
```
but the return is too long 
any way I can control the precision of the return value??
For example:
379.051757812 KiB  To  379.05 KiB

**Comment by tbielawa** [comment]
Sorry it took me so long to get back to you. Thanks for waiting :smile: 

Yes @tyan4g, complete control over result format is possible. Setting decimal precision is done through use of the [`format` method](http://bitmath.readthedocs.io/en/latest/instances.html#setting-decimal-precision). Here's an example for you:

```python
>>> import bitmath
>>> b_size = bitmath.KiB(379.051757812)

>>> # This is what you are seeing now:
>>> b_size.best_prefix()
KiB(379.051757812)

>>> # this truncates the decimal precision to just 3 digits and returns a string:
>>> b_size.best_prefix().format('{value:.3f} {unit}')
'379.052 KiB'
```

This method is similar to the native Python `format` method, and you feed it parameters in much the same way. The words you see in there, [`{value}`](http://bitmath.readthedocs.io/en/latest/instances.html#BitMathInstance.value) and [`{unit}`](http://bitmath.readthedocs.io/en/latest/instances.html#BitMathInstance.unit) are instance attributes of the object you are trying to format. The complete list of instance attributes is also documented for your perusal:

* [Bitmath Instance Attributes](http://bitmath.readthedocs.io/en/latest/instances.html#instances-attributes)

Bitmath also includes a [context manager](http://bitmath.readthedocs.io/en/latest/module.html#bitmath-format) to selectively change how bitmath instances are formatted. Using the `bitmath.format` context manager all printing and what have you inside of the context manager follows the specification you provide.

> bitmath.format([fmt_str=None[, plural=False]])

With this you can set the formatting string yourself, like the earlier example I showed with the `{value}` and `{unit}` attributes. You can also say that anything printed should use plural units (MiBs, kBs, etc). 

```python
#!/usr/bin/env python
import bitmath

def print_sizes(s1, s2):
    print """{}
{}
""".format(size1, size2)

size1 = bitmath.KiB(379.051757812)
size2 = bitmath.GiB(1)/3

print "Default precision:"
print_sizes(size1, size2)

print "3 digit precision:"
with bitmath.format('{value:.3f} {unit}'):
    print_sizes(size1, size2)

print "Plural units:"
with bitmath.format('{value:.3f} {unit}', plural=True):
    print_sizes(size1, size2)
```

And if you were to run this you would see results like such:

```Default precision:
379.051757812 KiB
0.333333333023 GiB

3 digit precision:
379.052 KiB
0.333 GiB

Plural units:
379.052 KiBs
0.333 GiBs
```

I hope that helps :+1: Please respond to this issue again if you have any more trouble. Thanks for using bitmath!

**Comment by kapsh** [comment]
@tbielawa thanks for explanation here, now I can find it in the documentation too: http://bitmath.readthedocs.io/en/latest/instances.html?highlight=precision#setting-decimal-precision
But this is very verbose and slightly inconvenient for frequent use. What do you think about adding `precision` argument to `best_prefix` method as shortcut for most commonly required operation?

**Comment by tbielawa** [comment]
I like your idea and want to find a way to implement what you're looking for. It can't be done the way you suggested but that doesn't mean it's impossible.

I made a new issue just now to track this (#64). Thanks for come back, I love community engagement!
