### ISSUE TITLE
Untagged release?

### ISSUE THREAD

**Issue by ddillard** [tbielawa/bitmath#63]
I see at https://pypi.python.org/pypi/bitmath that there's a release 1.3.1.2, however there is no such release in the NEWS file nor is there a release tagged.  I see a commit in the repository the same day pypi has 1.3.1.2 released so I think it's legitimate.  If it is can a 1.3.1.2 tag be created?

**Comment by tbielawa** [comment]
Sorry for the late response, this one got past me (holidays or something, I'm sure). I believe that was caused by a minor doc change.

I know it's late, but I pushed up a new tag for that commit!

**Comment by tbielawa** [comment]
Follow-up, when I cut the next official release I'll add a note in the NEWS file about the minor doc refresh that went into the 1.3.1.2 tag. Thanks for participating!

**Comment by ddillard** [comment]
Great.  Thank you!
