### ISSUE TITLE
Integration with argparse requires progressbar package

### ISSUE THREAD

**Issue by blochberger** [tbielawa/bitmath#86]
I am trying to use [`argparse` integration](https://bitmath.readthedocs.io/en/latest/module.html#argparse), but it turns out that one cannot import `BitmathType` without having the `progressbar` package installed.

Steps to reproduce:

```sh
python -m venv .tmp-env
. .tmp-env/bin/activate
pip install --upgrade pip setuptools wheel
pip install bitmath
python -c 'from bitmath.integrations import BitmathType'
```

This will raise the following error:

```
ModuleNotFoundError: No module named 'progressbar'
```

I do not think that the `progressbar` package is required.

Tested with Python 3.7.3 and `bitmath` 1.3.3.1 on macOS 10.14.5.

**Comment by tbielawa** [comment]
So sorry for the problem. You're absolutely right that this is a bug and
unexpected behavior.

I see the problem here. That was poor design choice on my part. I think I
can get a fix in this week.

Thanks for letting me know. I wonder how many other people got hit by this.
