### ISSUE TITLE
progressbar required when using click integrations even if progressbar integration not used

### ISSUE THREAD

**Issue by RhetTbull** [tbielawa/bitmath#96]
Even if progressbar is not used, using the click integration requires that progressbar be installed otherwise error:
"ModuleNotFoundError: No module named 'progressbar'" is produced.

It seems that progressbar shouldn't be required if not being used.  

OS: Mac OS 10.15.7
Python: Anaconda, Python 3.9.1 (default, Dec 11 2020, 06:28:49)
bitmath:  bitmath 1.3.3.1 

```pycon
>>> import click
>>> import bitmath
>>> from bitmath.integrations.bmclick import BitmathType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rhet/anaconda3/envs/osxphotos/lib/python3.9/site-packages/bitmath/integrations.py", line 29, in <module>
    import progressbar.widgets
ModuleNotFoundError: No module named 'progressbar'
```

**Comment by timlnx** [comment]
I am removing progress integration shipping as actual code in the bitmath-2.0.0 release. Instead the non-stdlib integrations will be shipped as code examples.

**Comment by RhetTbull** [comment]
Great! Thanks for fixing this.
